<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Automated Reports</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8ef5e8cf-1402-4d72-9d54-e2d68026e9e6</testSuiteGuid>
   <testCaseLink>
      <guid>e5c02633-977c-43b2-900d-979e646e9657</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>findTestObject('Automated Reports/Report Filters/filter_contentGroup')</defaultValue>
         <description></description>
         <id>44c90464-a1b0-4fab-8080-aad2ede06ec3</id>
         <masked>false</masked>
         <name>filter</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_browserOSversion&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Chrome-108-Windows 10&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0247a1a-63df-4ca6-836b-68bb095ea7e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_bucketSize&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Hours&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e900a1d0-8874-4374-bd29-f16c18763415</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_contentGroup&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;US&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>333c2460-cee9-4f3a-bc64-ce19032890b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_country&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;UNITED STATES&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92190f6b-30e9-48a9-9f38-ece70efe6d51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_granularity&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;1&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3cf4bb5-91ff-4535-84e6-04ec7cde5cfd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_netSpeed&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Cellular&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48ab87c8-a95e-46be-aa81-0b9cd1b8043e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_pageName&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;product&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78192b92-57bb-4359-b3cb-4966267191d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_region&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;VIRGINIA&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11178284-b070-45e6-856b-ad374751623e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_reportPercentile&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;95&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bf57c58-2707-4f58-a4d9-f36a64ae058c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestObject(&quot;Automated Reports/Report Filters/filter_trafficSegment&quot;)</value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;eCommerce&quot;</value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08d1ac18-b3af-4992-9bd0-f263a81a9710</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>14bc426f-4a2c-4b55-b0ad-494cd3b491a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Yes&quot;</value>
         <variableId>f77cd69a-b5de-48af-98d2-d6adc0d7b6a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f179af-6ce4-4eab-8e85-fc1bffea84c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34624204-61d4-4c14-8cb5-cab7492c7b01</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
