<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create All Reports</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a1da3f7f-cfd5-4c54-ba93-b72267cce9c1</testSuiteGuid>
   <testCaseLink>
      <guid>e560068f-7642-4eae-93fa-07ef3bd8856d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a6653cb-2570-4540-b7b6-d1cc0fca0b9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Synthetic Reports/Synthetic Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a990b06d-ede3-463a-bdbb-8e1419aac19c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e05e9cd-c209-46bd-8615-6f305dfb0105</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
