<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Executive Reports - Department Viewer - Elemis</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4d4d711f-ac96-4251-8fd3-04eaef7529d1</testSuiteGuid>
   <testCaseLink>
      <guid>c7fd3654-a466-43e6-93c7-f7f40b5fe752</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Executive Reports/Digital Experience Overview</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5bc55fe4-b5d6-4f0f-b0be-1862304cfcb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Executive Reports/Executive Crux Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;qa.vieweracct1&quot;</value>
         <variableId>f736292f-579e-4301-a845-55f7c5408ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8de625e8-bd3d-46c8-a70d-39cddc6d3252</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1451a420-ea5f-4276-8dd2-5291fc283bf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Executive Reports/Executive KPI Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c5418d-12c2-471d-a94f-be14c65e5a8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9395395-63f3-4482-928e-4adf78fb1d06</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
