<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Executive Reports</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e59142cf-64e6-43e3-90e0-bd93cc530b69</testSuiteGuid>
   <testCaseLink>
      <guid>002235e0-572f-4246-b580-6c326348312e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Executive Reports/Executive KPI Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c5418d-12c2-471d-a94f-be14c65e5a8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9395395-63f3-4482-928e-4adf78fb1d06</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0cc96974-a8ca-4b43-a3dc-bb45454d12e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Executive Reports/Executive KPI Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c5418d-12c2-471d-a94f-be14c65e5a8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9395395-63f3-4482-928e-4adf78fb1d06</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
