<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Real User Report Validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>49536cb1-1b40-42b2-a004-06e3f6115eef</testSuiteGuid>
   <testCaseLink>
      <guid>00f39f24-9331-4078-a9d3-5c64b4c568f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - 95th Percentile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c96d492-6ce2-4a21-bb06-23d7610e64af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9b0fd0c-c7cc-4740-86f5-f0322d93636a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f927e33a-bd76-48cb-9ffd-6e0c500cc8f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Browser_Version</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e9c9d49-aa28-4f4d-802d-4982f71460cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbba1a74-8d0e-4cec-b299-70da9c50f035</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0dacfaa-a9c0-441b-aa23-2926e8bc2f6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Bucket Size - Days</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a7eb219-4fce-4042-82cb-51bc2801450a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca9ed470-9698-4f1a-b5ad-e5ad7cb1ce21</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4613e5cf-8e96-44fe-a70c-c27626787461</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Bucket Size - Hours</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea217d84-7a12-4b20-aec9-0522a436d55e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ccd35c-4d84-4a76-bd99-29b48c453ea8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31583c89-bed4-4aa5-bfe3-6242390626e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Bucket Size - Minutes</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42500d7d-bc5d-4c5f-ae5c-f9393c7f7b8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72218401-b34c-42ea-bd5a-56bcecdb0c74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ce6ce11-9950-472f-9f00-047f0be7748c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Content Group_Page Group</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a07545ed-f959-4766-84da-b4a597d18ab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6422b7f7-b05a-46a4-ae84-4ee8412a3cf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6cc0988d-8676-4b6f-8b1d-bb1b7fbd3748</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Country</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>beb72245-6fe2-4df1-8154-829c6224a927</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce6e6d57-145b-4b0c-a4cf-40483531efce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf9e922a-1a70-4a71-8db8-d17a547483e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Granularity</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff1772ba-5b92-4183-824b-ad6709ea29d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>872dc929-ca2f-4a55-9359-ba08b02dc660</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e8b3a0-51d2-4950-8d9e-e88754d942b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6d950d2-9df1-4126-a386-f355d39cc700</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Include Screenshot</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edc4b2ec-f998-4b5f-9ffb-e5440685faf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>906567e3-9064-4bb1-ac26-cc96ba1a1960</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e6782e8-d69d-4602-9a40-3212dc0acf86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Net Speed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e65bd794-8a98-47f8-8f0b-88b2b8183e58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72ef2613-fcf8-4706-ab64-537c90df1984</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e77e0449-5a74-41a1-bdca-f18e30dc2c84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Region</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78e82af2-de99-481f-9679-9c6624843fad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35f878e-1c63-4880-90e5-98269ede98a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>425d5816-c5c0-4f7c-8483-7c0bd19eb841</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report - Traffic Segment Filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5440c05f-6c02-40fd-b68a-f9cf131d569a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc79f29c-94e4-428e-a23b-79c061d26423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4c45f86-c05b-45f7-8213-fc2e7c855ff6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Menu/Automated Reports/Real User Reports/Real User Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c9c75d5-783c-438e-8852-bc0d5a263783</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d84e0c6-3128-4c8c-abaa-24a72092aaf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44c90464-a1b0-4fab-8080-aad2ede06ec3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>566dd903-8316-4b06-aabe-516a47fb5fe4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
