<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Tag Testing - BTT Internal QA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>7d3073f7-e328-46bd-a508-75cd2298d3c7</testSuiteGuid>
   <testCaseLink>
      <guid>3c30b59b-8745-47b0-92ec-9d0dde200991</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Page Naming - Page Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a77703c-4368-49f7-9ada-1e0b3d7ed963</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2627bd84-daf9-4670-9433-17ec018bc836</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db56e6a9-7f1b-409e-baab-d278afe5b96a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b5bce10-89f6-4485-ae4c-05b5ab297075</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6290fbd5-0656-4755-bd73-9e9c1c8e6a92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08b25859-587b-4489-8fff-e3cedea0bee6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Page Naming - Partial String</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89fdf188-d2a8-46bd-a059-ff1e2e3f332c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62744507-d725-4faf-9c28-8c2ec3e49082</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6a25a40-95d4-44ca-b523-1ae88c0f4b64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81eef23a-9e24-4cf6-bac5-15c7f39505f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f07a236-95cf-4c0b-88f3-cc2ef8f0f08a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9beadc08-a216-4d31-a3b4-52a173eb3b98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Purchase Config Page Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd342bf5-eada-4642-a1fe-58b5397db33a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f1034eb-cd25-4979-90a7-de24e06cc9ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4758a437-d2f1-4d38-abc1-3a0ad05a8e61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6fe57f-6355-4633-94f8-b189a68f3a95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>740ab236-f0fd-4a65-9de8-8e9b8e895ce0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Thank You Collection Page Variable</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b30ab875-59da-4f5c-a8fc-9a0f7e8493d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19aca728-5c13-4aff-b4b5-18f615d53a99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d29e93b-ca4b-493f-9c68-56cbd92fa962</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>970bd606-49a7-426d-9c00-8d908d3616ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/SPA Page Naming - AJAX</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d947174e-833b-4931-870e-11df95998381</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b854212b-0ae6-4af2-bc1f-c7350cdca462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d1a15b-3a5e-4b71-aba9-f111622429d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14043f1b-a17c-40ca-977f-de5e318fe5ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acde40b-5a06-4ebc-8fa5-c512ac13a934</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27e0b8dc-fa81-40f6-a8ad-2eec770293cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/SPA Page Naming - Page Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee6602e3-be0a-40ba-8428-21a7ae8bd275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a083a87d-083c-40be-a660-cbb639c5193d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16337951-1250-4071-a45e-796ef6cd0ed2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>596f1efa-9900-4c3d-b697-d00a9a721dbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb719d56-38e8-4d15-9e0b-c052d1e2df38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32a226d4-fd70-459c-824e-4e32cc70e213</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Mutation Observer - End Selectors</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8a21575-78ca-4eb3-8652-24e529cef238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65855c91-f0d9-4d19-a9ef-a5c3b87e23b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6be302d2-0718-4692-bb35-120e429e67f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e624d427-6536-424c-9e28-4068e4b784d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ffde944-3cdd-422f-a103-d42a593ebe69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BT_Portal/Tag Testing/Mutation Observer - Page Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>758e8995-f6b3-43be-88cf-f3c3acd58a67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef80dedc-15c7-424b-98f6-2659b1f3abbb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49e228aa-309d-4ec6-bd55-b39f6f0e0713</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af3e305b-67b1-47ba-9e5c-f1a0848f3049</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
