<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Mobile</name>
   <tag></tag>
   <elementGuidId>627c8322-caef-428e-9fd3-e4934bf2f609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-controls-og&quot;]/div[4]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>executive-kpi-report-device-tab btn btn-default tab-btn center active</value>
      <webElementGuid>71c5a43e-81fe-4c5a-9023-5692e09c7567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd3bfb96-cde3-4340-b224-4db9ce010934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-device</name>
      <type>Main</type>
      <value>Mobile</value>
      <webElementGuid>5b665f29-4340-4fcc-889a-1694101ae3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-controls-og&quot;]/div[4]/button[2]</value>
      <webElementGuid>b524c3e1-faf3-4b7a-a236-c4dc8c9f81a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
