<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tablet Tab</name>
   <tag></tag>
   <elementGuidId>b1202c4b-602b-4fdf-9a5b-9c81cb42a90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-controls-og&quot;]/div[4]/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>executive-kpi-report-device-tab btn btn-default tab-btn right</value>
      <webElementGuid>63bc6128-52d3-4975-86db-412a361769b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32c935e5-cbc6-483f-9ae4-7d86b019b582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-device</name>
      <type>Main</type>
      <value>Tablet</value>
      <webElementGuid>4cbe8800-8679-4cb6-8fad-e2c986becc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-controls-og&quot;]/div[4]/button[3]</value>
      <webElementGuid>c17f9159-f691-41cb-b42d-857cbddf1a82</webElementGuid>
   </webElementProperties>
</WebElementEntity>
