<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply Filters</name>
   <tag></tag>
   <elementGuidId>5f1dcfb5-1919-4021-b30a-2404105eb6a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apply-filters</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='apply-filters']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b57ed2ba-44c7-40d1-9c69-72ccae6b8117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>d72f1e33-176d-4f3a-814f-f6a916a71390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Apply filter criteria and close filter pane</value>
      <webElementGuid>342271f2-a28c-4118-bb63-ce7ed13fe603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>be2514d3-08b0-4bea-974f-9a50eed50c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apply-filters</value>
      <webElementGuid>cbad7a2d-7a08-4063-85b2-a4dc7c8a0cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success pull-right</value>
      <webElementGuid>cfae029f-cf97-4953-8464-e242e42f1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c55129e5-016d-4a57-90a2-c9adc355a719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apply-filters</value>
      <webElementGuid>ab07384f-9081-476e-aedf-d25ddb3afb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply new filters</value>
      <webElementGuid>975bf410-caa9-426d-91e4-e97c3fe698a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>97785</value>
      <webElementGuid>aae73a97-3c17-4b95-9ba7-8d052e25081f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-term</name>
      <type>Main</type>
      <value>Apply filters</value>
      <webElementGuid>e6c6fe4f-226e-409d-ba5e-46e594aa8b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-definition</name>
      <type>Main</type>
      <value>Apply filter criteria and close filter pane</value>
      <webElementGuid>91f08740-8084-4c0f-8b1f-5334c00323aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip356019</value>
      <webElementGuid>cc726d38-532a-430a-82d2-02e072cc2e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Filters</value>
      <webElementGuid>243c6de8-c012-4d9c-955a-44b423c1776e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apply-filters&quot;)</value>
      <webElementGuid>b7423c38-44cb-45d1-807c-0ccfdb1ed7da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='apply-filters']</value>
      <webElementGuid>48f69f93-5e4e-48a1-a93e-3bf328754ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fp-form-buttons']/div/button[3]</value>
      <webElementGuid>e76d35a8-f6bd-4b1c-be45-7a2230375da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>4db05382-cdfd-48ae-971e-c39bb5ceae2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Genius Cache'])[1]/following::button[2]</value>
      <webElementGuid>c4d78b48-466f-4330-994a-970ea34891c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply filter criteria and close filter pane'])[1]/preceding::button[1]</value>
      <webElementGuid>89dd93af-7e7c-4178-b564-92c0dde20065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saved Filters'])[1]/preceding::button[1]</value>
      <webElementGuid>e48e6fcf-d353-4bd9-98a8-4518e4e3b7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Filters']/parent::*</value>
      <webElementGuid>69209ced-45e5-4f73-8485-19d239d37b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button[3]</value>
      <webElementGuid>a60b819d-0a4e-4457-8378-ca2a446f1e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'apply-filters' and @type = 'submit' and @name = 'apply-filters' and (text() = 'Apply Filters' or . = 'Apply Filters')]</value>
      <webElementGuid>991b9eeb-731c-4a72-8dab-e536a31b1190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
