<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_period</name>
   <tag></tag>
   <elementGuidId>54d6120b-e24a-4d3f-878e-cfad5acec375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#time-period-view</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='time-period-view']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d09a2ad3-5e1f-49c9-b075-597fee1643f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time-period-view</value>
      <webElementGuid>79dca0a8-1ec1-4d8d-925a-3912d460ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge has-interaction</value>
      <webElementGuid>d104154d-553f-44a6-94e6-19a5fb995e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 day  (2022-07-18 10:26 to 2022-07-19 10:26 EDT (-04:00)) </value>
      <webElementGuid>ee5c7749-11b5-413b-9942-683646028b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time-period-view&quot;)</value>
      <webElementGuid>502f81dc-4ebf-4d86-9c95-64c500f6652c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='time-period-view']</value>
      <webElementGuid>ab48fa71-60f6-43a8-b64d-0073af1c6ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-controls']/div/div[8]/span</value>
      <webElementGuid>8fe589a2-1fa3-4651-b536-ae1bfd2e86e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Period:'])[1]/following::span[1]</value>
      <webElementGuid>2bc15be0-1231-4805-8a08-a75b3d201e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule Applies From:'])[1]/following::span[2]</value>
      <webElementGuid>6ae8b0af-1a10-4229-8d2e-12a7b1fe64c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 day']/parent::*</value>
      <webElementGuid>a7820946-c65c-488f-9cb4-235bc6a4c59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span</value>
      <webElementGuid>1795a8ad-4b2b-4aaa-8d12-41353fda99c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'time-period-view' and (text() = '1 day  (2022-07-18 10:26 to 2022-07-19 10:26 EDT (-04:00)) ' or . = '1 day  (2022-07-18 10:26 to 2022-07-19 10:26 EDT (-04:00)) ')]</value>
      <webElementGuid>5ef54485-0f2f-45f3-9efa-f8cb29178fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
