<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time-period-icon</name>
   <tag></tag>
   <elementGuidId>612098cd-5703-41cf-bc93-23e3610cec5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#time-period-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='time-period-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f26f09d9-64fb-4fef-a8f8-a61470e7eb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time-period-icon</value>
      <webElementGuid>863bc3f9-b3fc-41be-b849-25bcd02d5c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon</value>
      <webElementGuid>8aaa92d2-e474-4c21-9de9-4d37b7ed2a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time-period-icon&quot;)</value>
      <webElementGuid>2bdab7fc-33dd-4be1-ab70-38c8eb9f276e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='time-period-icon']</value>
      <webElementGuid>f670c550-33b1-4530-81ac-96602356cf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='time-period-wrapper']/span</value>
      <webElementGuid>14527582-ec5e-43b6-be1d-7d9f9fc771d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Period'])[2]/following::span[1]</value>
      <webElementGuid>eef2d1ec-565c-4c58-9f7e-56a7d62dc1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Period'])[1]/following::span[1]</value>
      <webElementGuid>366e52a9-009f-4eaf-beb3-296b4cdf4632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timezone'])[1]/preceding::span[1]</value>
      <webElementGuid>e66db7f4-0df5-4692-a3d6-2457bc7d145f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='America/New York (-05:00)'])[2]/preceding::span[1]</value>
      <webElementGuid>e882efe2-098f-4a3b-afb1-c372f435236c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span</value>
      <webElementGuid>0c2fb7f1-bb7b-431f-ad0a-b5d39858d560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'time-period-icon']</value>
      <webElementGuid>1c43563c-3ba7-431f-b240-d0b1bb3bd989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
