<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_ROLES</name>
   <tag></tag>
   <elementGuidId>d7a03305-5680-4405-a482-5a31add2b01b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-access-and-roles']/div[4]/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f52bb941-38ad-4b0b-a707-1656325f05b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ROLES </value>
      <webElementGuid>beb6703c-2087-45bb-804f-ad4971fad2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-access-and-roles&quot;)/div[4]/div[@class=&quot;settings-header&quot;]/h4[1]</value>
      <webElementGuid>77f96bb3-3477-40b4-8da1-24ae3253ea4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-access-and-roles']/div[4]/div/h4</value>
      <webElementGuid>16bb557f-2b66-4b32-9b3e-18b3843cf8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create &amp; Edit Permissions'])[1]/following::h4[1]</value>
      <webElementGuid>a574faff-fed6-4c26-af73-eb83c0efad28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag Management Admin'])[1]/preceding::h4[1]</value>
      <webElementGuid>e5f8cf58-3646-43af-a020-9f7986a9edf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Admin'])[1]/preceding::h4[1]</value>
      <webElementGuid>3f9ec40d-ddbd-4dfb-bb92-48f25f68eebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ROLES']/parent::*</value>
      <webElementGuid>76f60df8-a555-4d2c-90fe-acb570a03d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/h4</value>
      <webElementGuid>48d86db9-5c2c-481c-8443-940ea5771ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'ROLES ' or . = 'ROLES ')]</value>
      <webElementGuid>621a161b-6eb8-4282-9d9f-3efb4b5120ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
