<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Usersusername</name>
   <tag></tag>
   <elementGuidId>5264fb19-5cac-49f1-b3c9-75f85294b13b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='users-username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#users-username</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'users-username' and @name = 'Users[username]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>032ea9ea-37e3-4c87-9741-472983cce59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>users-username</value>
      <webElementGuid>d8fdaa3c-b227-4f01-bc29-d25b944e4819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control required</value>
      <webElementGuid>d7c5796f-d9a3-4caa-b3b0-433e6e2114ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Users[username]</value>
      <webElementGuid>02af536e-7893-4173-81ba-b3f461a2b7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>752be174-b8bd-4e56-9680-379663e5b4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users-username&quot;)</value>
      <webElementGuid>b1c22d4e-cb17-47c8-a40e-2771ead504bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='users-username']</value>
      <webElementGuid>5c66c6cf-2fc2-4d60-a49c-4524a18a5768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/div[5]/div/input</value>
      <webElementGuid>bd76783d-8007-4faa-8362-fa1f2d40ef14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c5fd1e80-efa7-40b0-b9af-e3fcb66c99b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'users-username' and @name = 'Users[username]']</value>
      <webElementGuid>dd9d6c0d-1707-467a-9347-07bf5c57874a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
