<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a Department</name>
   <tag></tag>
   <elementGuidId>804b4ff6-60d2-47f8-ae10-f3f53b617370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='profiles-default_site']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profiles-default_site</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7299c68e-3c34-449c-a571-11289b49c56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profiles-default_site</value>
      <webElementGuid>ebe7e72e-e587-4e54-a1db-b457252a9713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e66c716-e6d8-4bdf-84d2-1b852d2a24ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Profiles[default_site]</value>
      <webElementGuid>bf9b2891-316d-4dc9-8540-860bbf4b9c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35dcc054-5f1c-4f15-a7d9-04002542df82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a Department</value>
      <webElementGuid>d109d55e-3aa2-4f35-993b-203fd4b24db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profiles-default_site&quot;)</value>
      <webElementGuid>e181ea63-1150-44af-ad4c-d25168c2b74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='profiles-default_site']</value>
      <webElementGuid>5d26339f-a280-4623-b756-0939e1e6e930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/div[11]/select</value>
      <webElementGuid>96fd7aaa-47e7-4044-8aa2-736efcbce16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Site'])[1]/following::select[1]</value>
      <webElementGuid>4b2ad180-57be-4b4a-a37b-e14715c0a702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name cannot be blank.'])[1]/following::select[1]</value>
      <webElementGuid>b098b489-cddb-4084-93a0-81bedd901431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landing Page'])[1]/preceding::select[1]</value>
      <webElementGuid>6b3777b6-34dd-4be0-9635-3754f0894566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Factor Auth Enabled'])[1]/preceding::select[2]</value>
      <webElementGuid>dd437219-e83f-4a3d-859a-5a0dfc83efa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/select</value>
      <webElementGuid>a336c253-7d8a-4bd0-9394-c4196630bf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'profiles-default_site' and @name = 'Profiles[default_site]' and (text() = 'Select a Department' or . = 'Select a Department')]</value>
      <webElementGuid>60775281-aa4a-4683-a38f-1bf8cfa9394c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
