<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Theme</name>
   <tag></tag>
   <elementGuidId>12d10d97-611d-41c3-aa99-9108b6329fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='users-theme']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#users-theme</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2fe8f7c4-d300-49ce-a33e-7392be440854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>users-theme</value>
      <webElementGuid>e6c9815e-0ef7-4889-858d-1e389a6fe031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4de38d9a-878a-4f6e-afb9-54885085fef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Users[theme]</value>
      <webElementGuid>28003042-2ec3-4195-8b15-102368a32151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>689fc6c8-ee2f-4706-bad9-a36374e7b4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simple LightLightDarkObsidian</value>
      <webElementGuid>f7f0b2b3-3d94-436a-8e4c-9308ac0e5fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users-theme&quot;)</value>
      <webElementGuid>c9f7bc1f-7ed4-4aca-94bf-33b8f209260b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='users-theme']</value>
      <webElementGuid>7f4f296b-ba7e-4bf7-ad2b-834e9456510d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/div[15]/select</value>
      <webElementGuid>f4de8504-9e24-4a23-9e6f-8812791ab8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme'])[1]/following::select[1]</value>
      <webElementGuid>7640193c-c465-4a82-a182-40b4c46f02c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Factor Auth Enabled'])[1]/following::select[2]</value>
      <webElementGuid>0d225adc-0136-40ab-8e43-a5535ad8d02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Type Preference'])[1]/preceding::select[1]</value>
      <webElementGuid>0539842e-3c0a-4b0c-8e5d-71905d1f7021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Style Preference'])[1]/preceding::select[2]</value>
      <webElementGuid>340bbbf4-b40f-499e-9141-e966a6f4b7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/select</value>
      <webElementGuid>7338efec-6e7c-41d8-bd45-832fc14c5467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'users-theme' and @name = 'Users[theme]' and (text() = 'Simple LightLightDarkObsidian' or . = 'Simple LightLightDarkObsidian')]</value>
      <webElementGuid>7653080c-8c0f-4134-9d6b-668c480a7d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
