<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Account</name>
   <tag></tag>
   <elementGuidId>0feca2ea-0003-424e-be51-7c8d69c2158c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-users-resellerid-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-users-resellerid-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;select2-users-resellerid-container&quot;)[count(. | //*[@id = 'select2-users-resellerid-container']) = count(//*[@id = 'select2-users-resellerid-container'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>57f98dee-d1af-4f06-b007-f36100951587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>84b845d6-7b4b-428e-8dbd-5808cb0a8e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-users-resellerid-container</value>
      <webElementGuid>b4e85b29-e23c-4de0-9b3b-49ecad6c544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Partner Test 11</value>
      <webElementGuid>d310ea71-8277-4357-bb9d-64448162db09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partner Test 11</value>
      <webElementGuid>ef0a2712-bf9c-4384-bc3c-20b2cf7c0507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-users-resellerid-container&quot;)</value>
      <webElementGuid>6c4f00d6-3195-42c6-b29d-b37ec156ef3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-users-resellerid-container']</value>
      <webElementGuid>36010b56-682b-4586-befd-513a7a774202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/div[3]/span/span/span/span</value>
      <webElementGuid>3440dcc7-2719-4a47-b488-0ceccef5ef32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::span[4]</value>
      <webElementGuid>c64acade-ca4a-4787-9433-18c5c5081372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::span[3]</value>
      <webElementGuid>26ab6576-239a-49cb-acfa-7b107545b799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>b7e6a710-8330-4ec6-bb6e-ca498b54d49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-users-resellerid-container' and @title = 'Partner Test 11' and (text() = 'Partner Test 11' or . = 'Partner Test 11')]</value>
      <webElementGuid>3712fc56-84de-437c-940b-68d1d413b3f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
