<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_LandingPage</name>
   <tag></tag>
   <elementGuidId>cc28d243-8492-4a0f-bd4c-bc1e2c04ecb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='users-landingpage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#users-landingpage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>138f42f2-5f35-4b83-81a7-3331a50754cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>users-landingpage</value>
      <webElementGuid>e83b9946-a33b-4ec9-8cb9-c5b1b24a58b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bba2f5b8-1f38-4b9b-b1de-500077679c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Users[landingPage]</value>
      <webElementGuid>413da4a0-b835-46ff-af19-15a6cf4d125f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e507e2f9-9e0f-4f4d-ae6b-c8bd2bf3b2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Digital Experience OverviewDashboardDigital Experience OverviewExecutive KPI ReportSlow PagesBrand OpportunityRevenue AttributionBrand AttributionRevenue AnalysisBrand AnalysisRevenue CalculatorBrand CalculatorMarketing OverviewMy CampaignsCustomer Journey AnalysisBrand Customer Journey AnalysisBottom of the Sales Funnel AnalysisRUM Performance OverviewRUM Performance DetailRUM Page Performance ComparisonRUM Aggregate WaterfallRUM Bounce &amp; Exit AnalysisRUM Javascript Errors &amp; CSP ViolationsNative App Performance OverviewRUM Native App Performance DetailRUM Native App Bounce &amp; Exit AnalysisSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsData Science InsightsTag Governance OverviewService ProfilesService DetailsDomain DetailsDomain TrendsSLA StatusSLA ThresholdsHierarchyInventory AnalysisDomain Baseline AnalysisMissing ServicesCSP OverviewCSP ManagerIssue TrackerAlertsReportsCompetitive Index TableCompetitive Index TrendsExecutive CrUX ReportBroken LinksOut Of Stock</value>
      <webElementGuid>24a11acc-0286-4940-b0e9-c37cd3e41ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;users-landingpage&quot;)</value>
      <webElementGuid>b5223e4f-a260-410f-9f12-9fbbbf38bf4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='users-landingpage']</value>
      <webElementGuid>9f35d005-6fbc-4297-a86a-e0a970b35886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/div[12]/select</value>
      <webElementGuid>a92e8bbf-2536-4704-9972-5c4d614387b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landing Page'])[1]/following::select[1]</value>
      <webElementGuid>8b02b735-0978-4a4a-bb9a-7b87db758d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Site cannot be blank.'])[1]/following::select[1]</value>
      <webElementGuid>2e100267-d88a-4c7e-8d24-e90f653278a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Factor Auth Enabled'])[1]/preceding::select[1]</value>
      <webElementGuid>676d102c-da39-49f9-9e8c-eb86a04ed173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme'])[1]/preceding::select[2]</value>
      <webElementGuid>21778be9-d540-48de-baa8-13f2309bbd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/select</value>
      <webElementGuid>3213e8ff-bc77-4d15-9872-b21fd929bea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'users-landingpage' and @name = 'Users[landingPage]' and (text() = 'Digital Experience OverviewDashboardDigital Experience OverviewExecutive KPI ReportSlow PagesBrand OpportunityRevenue AttributionBrand AttributionRevenue AnalysisBrand AnalysisRevenue CalculatorBrand CalculatorMarketing OverviewMy CampaignsCustomer Journey AnalysisBrand Customer Journey AnalysisBottom of the Sales Funnel AnalysisRUM Performance OverviewRUM Performance DetailRUM Page Performance ComparisonRUM Aggregate WaterfallRUM Bounce &amp; Exit AnalysisRUM Javascript Errors &amp; CSP ViolationsNative App Performance OverviewRUM Native App Performance DetailRUM Native App Bounce &amp; Exit AnalysisSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsData Science InsightsTag Governance OverviewService ProfilesService DetailsDomain DetailsDomain TrendsSLA StatusSLA ThresholdsHierarchyInventory AnalysisDomain Baseline AnalysisMissing ServicesCSP OverviewCSP ManagerIssue TrackerAlertsReportsCompetitive Index TableCompetitive Index TrendsExecutive CrUX ReportBroken LinksOut Of Stock' or . = 'Digital Experience OverviewDashboardDigital Experience OverviewExecutive KPI ReportSlow PagesBrand OpportunityRevenue AttributionBrand AttributionRevenue AnalysisBrand AnalysisRevenue CalculatorBrand CalculatorMarketing OverviewMy CampaignsCustomer Journey AnalysisBrand Customer Journey AnalysisBottom of the Sales Funnel AnalysisRUM Performance OverviewRUM Performance DetailRUM Page Performance ComparisonRUM Aggregate WaterfallRUM Bounce &amp; Exit AnalysisRUM Javascript Errors &amp; CSP ViolationsNative App Performance OverviewRUM Native App Performance DetailRUM Native App Bounce &amp; Exit AnalysisSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsSynthetic Performance OverviewSynthetic Performance DetailSynthetic Test ResultsSynthetic Page Performance ComparisonSynthetic Aggregate WaterfallSynthetic Javascript Errors &amp; CSP ViolationsAPI Check OverviewSynthetic API Check PerformanceSynthetic API Check Test ResultsNetwork Health Checks OverviewSynthetic Network Health Checks PerformanceSynthetic Network Health Checks Test ResultsData Science InsightsTag Governance OverviewService ProfilesService DetailsDomain DetailsDomain TrendsSLA StatusSLA ThresholdsHierarchyInventory AnalysisDomain Baseline AnalysisMissing ServicesCSP OverviewCSP ManagerIssue TrackerAlertsReportsCompetitive Index TableCompetitive Index TrendsExecutive CrUX ReportBroken LinksOut Of Stock')]</value>
      <webElementGuid>f5bb69b1-3d09-4b5f-aa3d-d6b9c9ea60d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
