<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_spline</name>
   <tag></tag>
   <elementGuidId>b6e3bc34-8cdf-4f94-988b-13a98686ce77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@name='spline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[name=&quot;spline&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a53a884-a794-4dfd-8cbd-f01635ab1d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active left btn btn-default tab-btn</value>
      <webElementGuid>aacfc638-f1dd-48ae-a71b-8e07b6c0d6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Spline</value>
      <webElementGuid>d8891431-76d1-4467-a6a4-4856a8b60ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spline</value>
      <webElementGuid>a7935be5-da1d-4c74-ba53-6bbc8d2fbccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;general-configuration&quot;)/span[@class=&quot;active left btn btn-default tab-btn&quot;]</value>
      <webElementGuid>d749b70b-d049-4605-8039-ef6eced32730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@name='spline']</value>
      <webElementGuid>703ea2f5-23b7-44fa-9a50-0b7cf0716d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/span</value>
      <webElementGuid>4520bbeb-d618-49b4-aa8f-51425c33ec68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Style Preference'])[1]/following::span[1]</value>
      <webElementGuid>4fe0491d-e014-412a-adb3-509448e0bf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Type Preference'])[1]/following::span[1]</value>
      <webElementGuid>c11d9abf-844d-413c-8056-21da92b150a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE &amp; EDIT PERMISSIONS'])[1]/preceding::span[2]</value>
      <webElementGuid>dfbe75a4-8dcd-4ec3-8f74-8301373d8b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/span</value>
      <webElementGuid>439005bb-d95e-41d1-b0fc-0704b0224c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Spline' and @name = 'spline']</value>
      <webElementGuid>5fb0fe94-78f1-4fb4-a019-4f91146227f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
