<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_line</name>
   <tag></tag>
   <elementGuidId>8df6862a-843b-4633-ae4c-55ed0ab67962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@name='line']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[name=&quot;line&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c9466a5-22e3-4dec-8f8d-d0ca48b092cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right btn btn-default tab-btn</value>
      <webElementGuid>e14425e8-3242-4475-bc91-f9d2b42a4617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Line</value>
      <webElementGuid>8d5fee73-4ed2-4189-9c93-520c277a5c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>5a8ccdd0-8a36-4960-ba50-c56d81e8cd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;general-configuration&quot;)/span[@class=&quot;right btn btn-default tab-btn&quot;]</value>
      <webElementGuid>ab2f1847-ed23-406d-9eb8-56e488157e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@name='line']</value>
      <webElementGuid>5ac39cb7-763f-4b2e-8ea4-3d78374b0a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='general-configuration']/span[2]</value>
      <webElementGuid>97090287-82c6-40e2-8b19-95738d328d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Style Preference'])[1]/following::span[2]</value>
      <webElementGuid>600dcba4-5b3b-40a6-a798-901c56c628b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chart Type Preference'])[1]/following::span[2]</value>
      <webElementGuid>d4c3c1d3-b538-4825-bf82-29546f4fe99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREATE &amp; EDIT PERMISSIONS'])[1]/preceding::span[1]</value>
      <webElementGuid>1b4a1719-a0f4-46c8-9542-c765f46f17b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>8c396313-920c-46cb-a7f4-9a8a27e15d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Line' and @name = 'line']</value>
      <webElementGuid>b55a2c4b-b078-4b3a-ae89-fcae8491d977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
