<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lookback</name>
   <tag></tag>
   <elementGuidId>238cda9a-5844-4d4f-a9cd-3aba52f471a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#time-lookback</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='time-lookback']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96012363-784b-48a7-a08d-97f1f157c0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default dropdown-toggle</value>
      <webElementGuid>cb3cdc7e-3ade-421a-8b08-869ddb90cd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time-lookback</value>
      <webElementGuid>72649d1b-345d-47e9-b303-8c90ece61e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf0cbee2-d14a-4265-b5ce-df433ee4a7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>3a0e0844-c1ca-4fa4-9ec1-a1930ab57dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f14f843a-5fd3-4a13-bf05-3fa5c578500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Last 2 days</value>
      <webElementGuid>674275be-f855-4319-912f-4e4024037a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last 2 days

</value>
      <webElementGuid>52d61afb-f52a-4bb3-bc38-980376bc8ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time-lookback&quot;)</value>
      <webElementGuid>b202e838-5716-4f72-a49b-fafdd98a43c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='time-lookback']</value>
      <webElementGuid>0e1f1b51-5659-4301-a807-6f7e2728f591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-controls-og']/div/div[3]/button</value>
      <webElementGuid>d263248d-f18a-4c3f-80f6-dcda499ac390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo eCommerce Global'])[5]/following::button[1]</value>
      <webElementGuid>a7bd8be5-bd2c-4cb5-8df6-4e7fb2e59dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_BTT Synthetic Performance Overview'])[2]/following::button[1]</value>
      <webElementGuid>8cbdcb81-1bc6-4ae3-84a6-7cc941135ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Date Selection'])[1]/preceding::button[1]</value>
      <webElementGuid>4dde26a8-8424-4c21-9c64-e5f2c32b8a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>12c3acf8-8c7c-4e51-8dd6-c2e77cc2b960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'time-lookback' and @type = 'button' and (text() = 'Last 2 days

' or . = 'Last 2 days

')]</value>
      <webElementGuid>599ac838-daef-4fa8-81dd-14a7f451b0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
