<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loading-icon-wrapper</name>
   <tag></tag>
   <elementGuidId>3f20aeaf-6f1e-4aea-a037-480675daf6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef10e5e9-09c9-49ce-b9eb-11b52d5779f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading-icon-wrapper</value>
      <webElementGuid>e8e8174f-2f7e-461a-86d7-7686264831cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;loading-icon-wrapper&quot;]</value>
      <webElementGuid>dbf5f78b-3a54-4081-8b78-d48739837cec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
