<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_menu</name>
   <tag></tag>
   <elementGuidId>e123736c-7646-4c33-a62f-0721610787ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='toggle-navigation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggle-navigation</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'toggle-navigation' and @name = 'Toggle menu visibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff235491-c386-4335-ab3c-c6c4eecb41e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-navigation</value>
      <webElementGuid>dc63c300-5655-4c3b-82f5-af129fdd21fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Toggle menu visibility</value>
      <webElementGuid>df497636-cff6-4f3f-948b-69fe37204801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle menu visibility</value>
      <webElementGuid>34bad4a7-add5-4be6-99f1-558d45fede4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hamburger hamburger--3dy js-hamburger ctrl r-p pull-left bt-menu-toggle</value>
      <webElementGuid>2ba66008-867b-4d90-9fbf-7add636de954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-navigation&quot;)</value>
      <webElementGuid>101c20e4-0cc6-4213-9d73-c2ba77462e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='toggle-navigation']</value>
      <webElementGuid>79b6c79f-52c6-4146-9af1-1f1c44c829c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/button</value>
      <webElementGuid>c626ccb2-f908-4d78-93a6-f0db0c076b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lowes'])[2]/preceding::button[1]</value>
      <webElementGuid>f13185f3-b224-499e-87f1-34227fc1479e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Experience Overview'])[2]/preceding::button[1]</value>
      <webElementGuid>4359d132-f916-4f98-ade4-83f5baa4e4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a68a8872-60e4-4e8e-b64c-f43d8b5c5838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'toggle-navigation' and @name = 'Toggle menu visibility']</value>
      <webElementGuid>f9f10b9a-5fd1-4a19-8dd6-2c024c37c4e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
