<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_loading-icon</name>
   <tag></tag>
   <elementGuidId>9dd057cf-f157-4a23-9073-81b4cd979154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'highcharts-loading']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.loading-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='343184-1653334675']/div[7]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6124ea31-94ed-47b9-9943-14c7ff47e55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-loading</value>
      <webElementGuid>3ccbf34b-e0d0-4954-a837-333f0a805899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;343184-1653334675&quot;)/div[@class=&quot;loading-icon-wrapper&quot;]/div[@class=&quot;loading-icon&quot;]</value>
      <webElementGuid>64548bff-95a8-4edb-9ac8-a058b53e0bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='343184-1653334675']/div[7]/div</value>
      <webElementGuid>b6662863-2da4-42d7-a8f3-23eaae93e2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance'])[1]/following::div[8]</value>
      <webElementGuid>3e6d42df-694b-4b89-b84e-efa699771317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Dashboard'])[1]/following::div[20]</value>
      <webElementGuid>8217e4ed-6309-4ca8-b08c-c6b15b10b6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device Metrics'])[1]/preceding::div[5]</value>
      <webElementGuid>2a1305a1-b935-49ed-b624-f2d2ec7693a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geography'])[1]/preceding::div[21]</value>
      <webElementGuid>6faf5ae1-bb19-444a-ad91-7b115dc07c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div</value>
      <webElementGuid>f102e471-b23a-47bc-a7ec-9091bea649c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
