<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HTML</name>
   <tag></tag>
   <elementGuidId>52afbf3a-b4f0-4f44-86b3-f2ee3b8f2341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body-html</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='body-html']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba91629d-59a7-4ccc-8efd-6cd6377c2a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body-html</value>
      <webElementGuid>6b2fd191-8cf9-430e-8629-aab26178191a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2e77ca5-5d5c-446d-8ac3-9462a0338420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default active</value>
      <webElementGuid>ce2b90c0-c1f2-4de0-8d7a-484058014ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTML</value>
      <webElementGuid>7b5faf86-8217-4cda-b536-a081020947c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-html&quot;)</value>
      <webElementGuid>b94f3f3b-b066-4b0d-84e2-9b4042589e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='body-html']</value>
      <webElementGuid>d905f7fa-c611-4dd1-aa29-653f59754625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-body-row']/div/label/div/button</value>
      <webElementGuid>fd335d50-7e09-48ec-ae37-8384fd7d5fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include With Custom Subject:'])[1]/following::button[1]</value>
      <webElementGuid>7a3d7b01-e04e-468b-943e-55e1e891eb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plain Text'])[1]/preceding::button[1]</value>
      <webElementGuid>6495a90e-2d53-4d94-9d12-3cb09b46243c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HTML']/parent::*</value>
      <webElementGuid>b48d36ad-5244-4ed1-a349-d461cbbaeb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/button</value>
      <webElementGuid>60cd8ea2-d540-4c84-b54a-10cc87ae4759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'body-html' and @type = 'button' and (text() = 'HTML' or . = 'HTML')]</value>
      <webElementGuid>866a5b53-d383-45fe-b06a-4ca68982a69e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
