<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Plain Text</name>
   <tag></tag>
   <elementGuidId>762b1c68-524c-4d96-b827-e69ec5f5b3f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#body-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='body-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0183ffc9-0bb8-4721-9c1a-86a1e6c17136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>body-text</value>
      <webElementGuid>d1f27452-8772-4c60-bee5-e705536fa061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f55a267a-8385-4bfb-b9dd-663d736f549f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>ab4369b0-4ead-4580-995b-14e005e250d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plain Text</value>
      <webElementGuid>d3eb1cb9-d992-4b38-8851-cdf46095986c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-text&quot;)</value>
      <webElementGuid>b212e315-c309-45a8-b263-a736da0ea0de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='body-text']</value>
      <webElementGuid>8340137a-122f-49f1-8e10-fc2019601f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom-body-row']/div/label/div/button[2]</value>
      <webElementGuid>fcf6e7c8-38ec-43e0-b64e-a40f1ec8e2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HTML'])[1]/following::button[1]</value>
      <webElementGuid>3c088018-938a-4001-8612-6e1a56b224b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::button[1]</value>
      <webElementGuid>280f7408-35d2-4dcb-8153-ca3610da9698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Plain Text']/parent::*</value>
      <webElementGuid>647ef721-6b15-4ad7-8770-3348e41b9f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/button[2]</value>
      <webElementGuid>8f521d64-0f62-4e85-92e5-61d2b4c9972b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'body-text' and @type = 'button' and (text() = 'Plain Text' or . = 'Plain Text')]</value>
      <webElementGuid>7263fb43-1f10-4dc9-bbdf-935f1981120c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
