<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sms-integration</name>
   <tag></tag>
   <elementGuidId>245ef3c9-b59a-4b97-a044-b269435a260b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sms-integration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sms-integration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86771061-3479-4df7-bdfb-63606e4ea8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>967300f4-b6ef-49e4-ad1b-82a8451ea425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sms-integration</value>
      <webElementGuid>62df179c-aab3-4ab2-9ede-82501469454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4b266cf3-ef6c-4df9-8ea7-275a02d9b87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sms-integration</value>
      <webElementGuid>a5898b1e-684d-4802-ac9a-6819930ef65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter phone numbers for SMS messages</value>
      <webElementGuid>b105e4e3-79da-4ea7-859a-9abc78260464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sms-integration&quot;)</value>
      <webElementGuid>3398fae1-cd63-44b7-a594-407d12fcc54b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sms-integration']</value>
      <webElementGuid>4ef9bb55-f4bf-4091-8b84-2c1634a6041b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sms-integration-row']/div/input</value>
      <webElementGuid>d5482e97-30da-4cf9-9955-9a4f26115612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>a9896ffc-0793-4aa5-b6c6-9109b329811a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'sms-integration' and @name = 'sms-integration' and @placeholder = 'Enter phone numbers for SMS messages']</value>
      <webElementGuid>c686ca8d-817b-47d6-9758-1bf1990625b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
