<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subject Line</name>
   <tag></tag>
   <elementGuidId>bcf1be5d-5064-41b3-bc15-eb560fae566e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subject-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subject-line']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>491de53a-1f04-4869-8d51-0e51dadcbe39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7be0e637-ac27-493f-a553-129bb3ac2323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subject-line</value>
      <webElementGuid>9f840000-7781-4ae0-a7a8-c9722eebfc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Leave blank for default subject line</value>
      <webElementGuid>80eadc47-5bad-44ca-ab27-c4748abdd43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>690b7ea5-8766-44b9-9932-e435b4ef3fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subject-line</value>
      <webElementGuid>d62798a5-3a38-4ea5-b8c7-92e2221677bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subject-line&quot;)</value>
      <webElementGuid>2a086c33-b37a-4902-bc9f-054ff5cccacf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subject-line']</value>
      <webElementGuid>6dc96ba0-3181-4d09-bae6-dc2d7518000d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subject-line-row']/div/input</value>
      <webElementGuid>f05f511d-d4fa-4a43-9784-a8fd5f53c9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>3e935b36-de63-4a23-904c-953b05123e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'subject-line' and @placeholder = 'Leave blank for default subject line' and @name = 'subject-line']</value>
      <webElementGuid>530716e4-ba10-45b9-bac3-ab1bfc370c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
