<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Configure a webhook_slack-integration</name>
   <tag></tag>
   <elementGuidId>3e9a6d09-7ebe-45dd-92de-4d53ed4b9410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slack-integration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='slack-integration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33c64459-bc57-4a58-9a29-1818eb02dc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9391d18-f492-457a-91f1-b07f85a4f12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slack-integration</value>
      <webElementGuid>5a22d8f4-6556-4712-b4a9-0d6a5b625fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4bffc4b6-da93-4056-9872-d325bd0128ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>slack-integration</value>
      <webElementGuid>a46af538-6a9c-4cda-94e2-b4b81ea346ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Webhook URL (https://hooks.slack.com/services/...)</value>
      <webElementGuid>7ba5630e-152b-43da-bdc5-a5d8ef57a942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slack-integration&quot;)</value>
      <webElementGuid>4bf72cb9-fa35-4e0c-956f-d0ed1f2e049b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='slack-integration']</value>
      <webElementGuid>58227534-6e8f-49b8-b0e0-a8ec8ab7efe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slack-integration-row']/div/input</value>
      <webElementGuid>17fd1805-b545-491e-9332-1ff43029299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>f163c480-a3ba-48e2-8761-6564a0c6cfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'slack-integration' and @name = 'slack-integration' and @placeholder = 'Enter your Webhook URL (https://hooks.slack.com/services/...)']</value>
      <webElementGuid>81c45f5b-43f1-454a-9d32-ee5ee35ec24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
