<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__recipients</name>
   <tag></tag>
   <elementGuidId>5564c491-86e3-491b-ba1b-32210241801d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recipients</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recipients']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f597eef-f74c-4a77-8ca9-7a85b6e4b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cbee625-6c1a-48aa-b23c-98519565a775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recipients</value>
      <webElementGuid>b64a7c0f-c52f-4dbc-8d06-b589dd7b4591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>173a7ab6-47b9-426e-a617-705d2deaf25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>recipients</value>
      <webElementGuid>9a4c1a8d-424c-4268-a26c-6c0dfaf104a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email addresses separated by commas</value>
      <webElementGuid>3ac42d3b-ee62-4073-a34c-6d31e10b4439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recipients&quot;)</value>
      <webElementGuid>080f14a5-ef56-43b9-ac86-d6a093e81fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recipients']</value>
      <webElementGuid>329db810-766b-42c8-a9b7-4b2572dafd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recipients-row']/div/input</value>
      <webElementGuid>11128183-75d0-44d1-b7a9-8aaf672fa9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ada11025-3f77-4bc5-8638-0c3095edadab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'recipients' and @name = 'recipients' and @placeholder = 'Enter email addresses separated by commas']</value>
      <webElementGuid>8bcdd7e9-3999-4322-a03f-d43ff2499671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
