<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__alert-name</name>
   <tag></tag>
   <elementGuidId>6e4bf2e3-5959-408a-8c13-3e547d60f146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alert-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alert-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0e6deb4-8477-4723-81cb-f9ec7927c666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de68beac-af26-4d83-b2e2-4211da6e57e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alert-name</value>
      <webElementGuid>089002f9-ce34-45c9-b011-1ef04e5e24f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ef088e3-82a1-452b-a262-4eab21143d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alert-name</value>
      <webElementGuid>83c2ece9-bf86-44bd-87c0-3b694300a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter an alert name</value>
      <webElementGuid>60894641-8277-4628-8e25-48a3148cda28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alert-name&quot;)</value>
      <webElementGuid>e06c5a47-d3ea-4364-9cde-4750f1ac7491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alert-name']</value>
      <webElementGuid>226f72a1-15b6-4dcb-bd7b-60fc94c933f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-name-row']/div/input</value>
      <webElementGuid>04810ce5-e786-4993-b437-75d6aa1a717b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ed415035-9f10-4038-9675-c5e27e36a449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'alert-name' and @name = 'alert-name' and @placeholder = 'Enter an alert name']</value>
      <webElementGuid>b9993ca3-2cc6-4306-887d-93cdf87d74f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
