<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Enabled</name>
   <tag></tag>
   <elementGuidId>581417ce-5855-44ac-af3a-ec57c1c10557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-alert-enabled-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-alert-enabled-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eacff533-541a-4556-af44-1bd15c2be2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>492443cd-daea-4d87-9aa2-4a1849ecdfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-alert-enabled-container</value>
      <webElementGuid>7025b1b5-ea4b-4c1d-8114-dd82c9a9e752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enabled</value>
      <webElementGuid>37af4641-3e6b-4b04-b62a-e3a91b8747e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enabled</value>
      <webElementGuid>8ff48cb4-82c2-4e5f-9c76-76a3df21e45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-alert-enabled-container&quot;)</value>
      <webElementGuid>b59370df-0855-4172-9be0-2947863b5a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-alert-enabled-container']</value>
      <webElementGuid>2af7a51b-c57a-4055-9f9a-fd8bf1141a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alert-enabled-row']/div/span/span/span/span</value>
      <webElementGuid>0f8e9c16-53cd-42ee-8556-158b23738650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert Status:'])[1]/following::span[4]</value>
      <webElementGuid>fb12ce7f-8e5a-42ad-bc3e-01b3c27b2adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[4]</value>
      <webElementGuid>9e761e40-dca0-4df3-b1e7-1b95a56c7ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[3]</value>
      <webElementGuid>207eed57-be87-4ce6-b7fc-27454bb61747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/span/span</value>
      <webElementGuid>cd01bbd6-ec44-4d5f-a6ef-02efd5ac92da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-alert-enabled-container' and @title = 'Enabled' and (text() = 'Enabled' or . = 'Enabled')]</value>
      <webElementGuid>dd2b6f7f-1612-49bf-879c-308cc51cd33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
