<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Graph</name>
   <tag></tag>
   <elementGuidId>aca2b5b1-adb7-4ca7-b77d-10c936291e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap.select2-container--focus > span.selection > span.select2-selection.select2-selection--single</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='include-screenshot-row']/div/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45fee5d4-3237-497f-9e34-72efacfbace7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>5d0388ec-00f3-4352-992c-9c1474f502e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>ba6b5bdf-af49-4c7e-9375-ba8499eda80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>842a8544-72de-4132-9391-fb7c151e5c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>778535b6-b0d7-4665-8a8c-8c2dd38eba63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e9e005a-df3c-4249-8fc8-a7f37688ef5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-include-screenshot-container</value>
      <webElementGuid>1a8b9721-af54-47ef-883a-18a48373a074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No, don't include the graph</value>
      <webElementGuid>63eb69e5-5147-4032-9b15-d9892f096809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;include-screenshot-row&quot;)/div[@class=&quot;col-xs-12&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]</value>
      <webElementGuid>8251c215-1832-4cd8-8c9f-d2e9fb973814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='include-screenshot-row']/div/span/span/span</value>
      <webElementGuid>22a3849d-36e2-4a69-9685-93143e32f4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Would you like to include a graph in the alert?'])[1]/following::span[3]</value>
      <webElementGuid>bc867701-d9a1-4c73-87cb-df4c91646789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configure a webhook'])[1]/following::span[3]</value>
      <webElementGuid>6487e450-d94d-43b2-8bdd-111b568fbd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject Line:'])[1]/preceding::span[4]</value>
      <webElementGuid>163c14f5-15b3-4db9-991e-d53e4071a9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span/span/span</value>
      <webElementGuid>082ef787-df27-42d8-be0a-d3f60e75a280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = concat(&quot;No, don&quot; , &quot;'&quot; , &quot;t include the graph&quot;) or . = concat(&quot;No, don&quot; , &quot;'&quot; , &quot;t include the graph&quot;))]</value>
      <webElementGuid>d1a7ec83-b061-4df3-be49-918c3b67d976</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
