<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dashboard</name>
   <tag></tag>
   <elementGuidId>697074e6-cb20-4617-a39e-471296191826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-dashboard-page-controls']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create-dashboard-page-controls</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5ea1bca-f369-4c99-9350-292955a4391c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-dashboard-page-controls</value>
      <webElementGuid>28e5e477-2e45-4541-8f07-f65f7d0a7d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary create-dashboard-btn</value>
      <webElementGuid>35e50851-cce6-45ba-b543-ab618ec91b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>070823b9-d9ce-4148-bf6d-1e7d4fb4b1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create a new dashboard</value>
      <webElementGuid>4902c533-a97c-450c-9a8c-3b079cbfa699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Dashboard</value>
      <webElementGuid>1a011e99-dde7-4c44-9f41-2b758ce67a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-dashboard-page-controls&quot;)</value>
      <webElementGuid>e1bb4f2c-59ae-4050-bc7b-b92f2a7c64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17137e61-d476-44f0-b867-a898933e2ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-dashboard-page-controls</value>
      <webElementGuid>60eb7619-4a04-4564-a030-d72a140dad7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary create-dashboard-btn</value>
      <webElementGuid>3cb15649-161b-4c47-bd98-9d3e1c01ffa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34a7cb4e-2f01-4e98-9cf1-c474e7aec7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create a new dashboard</value>
      <webElementGuid>b077d064-641a-4b77-86af-30a2b1be6b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Dashboard</value>
      <webElementGuid>f30d7ac3-2805-40d9-8e64-25b64df40e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-dashboard-page-controls&quot;)</value>
      <webElementGuid>1e8bc69d-6911-44c3-9a1d-4278bc4dc104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-dashboard-page-controls']</value>
      <webElementGuid>50ef923a-2251-459e-b882-8b818d2dc744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-manager']/div[2]/button</value>
      <webElementGuid>b46b16a4-4d87-43be-a08b-f773350f2732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Widget'])[1]/following::button[1]</value>
      <webElementGuid>bc58b8f4-8534-40fe-8830-7f393f86d55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance'])[1]/preceding::button[3]</value>
      <webElementGuid>5c3fcebf-4e8b-44d5-a3bd-6729bb462bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deselect All Metrics'])[1]/preceding::button[4]</value>
      <webElementGuid>238a76cb-75c9-4e24-bc52-5fdf7a01a383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Dashboard']/parent::*</value>
      <webElementGuid>01ef9ec8-ee15-414b-80f7-d4347d10b0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>f6bdba15-dc8f-4864-a126-98bbebf115d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'create-dashboard-page-controls' and @type = 'button' and @title = 'Create a new dashboard' and (text() = '+ Dashboard' or . = '+ Dashboard')]</value>
      <webElementGuid>8d5fc882-fea2-4e75-9f2d-d43226ee483f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
