<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_(Myself)</name>
   <tag></tag>
   <elementGuidId>5a1bc313-a049-4ffd-9068-3a6baea411af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-users-for-cloning-dashboard-result-a8qc-344787']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '(Myself)' or . = '(Myself)')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-users-for-cloning-dashboard-result-a8qc-344787</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(Myself)</value>
      <webElementGuid>f28ddfde-e1d8-46c6-bddd-ca5fa7213c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-users-for-cloning-dashboard-result-zkfc-344787&quot;)</value>
      <webElementGuid>7b47458a-ac32-4bda-a11d-881998b600e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-users-for-cloning-dashboard-result-a8qc-344787']</value>
      <webElementGuid>f4015643-22f6-4be4-b4dc-b5bdddc0fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-users-for-cloning-dashboard-results']/li</value>
      <webElementGuid>fa285cba-5be7-4071-8845-dbec7afd98f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::li[1]</value>
      <webElementGuid>1fd5faf5-85b8-442d-b58a-b72c488b6adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin admin (Account Admin)'])[16]/preceding::li[1]</value>
      <webElementGuid>83929513-d77d-426b-97e2-f39c53f5d46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin admin (Account Admin)'])[17]/preceding::li[3]</value>
      <webElementGuid>4d9f2a0a-7d38-48e5-bf08-acffe1406595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/ul/li</value>
      <webElementGuid>85fabfe7-a8e2-45dd-a1ad-cb8705271e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-users-for-cloning-dashboard-result-a8qc-344787' and (text() = '(Myself)' or . = '(Myself)')]</value>
      <webElementGuid>a167f6bd-8102-4a5d-a429-dc25a6f966a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-users-for-cloning-dashboard-result-zkfc-344787']</value>
      <webElementGuid>a0eb9884-dd4d-41b6-855c-a3f10cf7cbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[2]/following::li[1]</value>
      <webElementGuid>4414f495-a343-4453-b9ff-25a19d93bc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-users-for-cloning-dashboard-result-zkfc-344787' and (text() = '(Myself)' or . = '(Myself)')]</value>
      <webElementGuid>62a55604-7474-430e-be76-a11c9591911e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-users-for-cloning-dashboard-result-d9ub-344787']</value>
      <webElementGuid>b251d258-4d7b-41ee-88bb-1ef03b59171f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-users-for-cloning-dashboard-result-d9ub-344787', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>5e46d21f-7af6-4c8a-a3af-3ef2e12ffdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::li[1]</value>
      <webElementGuid>6950ae82-7411-4c8a-a2e3-9effa60efde9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-users-for-cloning-dashboard-result-d9ub-344787' and (text() = '(Myself)' or . = '(Myself)')]</value>
      <webElementGuid>d9cf10c3-88ac-4544-b181-6d5eaf7bd048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
