<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bulk Actions</name>
   <tag></tag>
   <elementGuidId>d0c93ad5-673c-47ba-96f8-975fa02e878e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;page-controls-og&quot;]/div/div[1]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulk Actions</value>
      <webElementGuid>02e9449a-2956-4e25-b0a6-954995eb9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>dae2b7f3-81a2-4f61-b98e-d03f33f38e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c30ddda-c108-4a9d-9344-116e3ca8ccca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-controls-og</value>
      <webElementGuid>bcf8da2c-8ea0-4352-b0ed-64ad7d1002fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;page-controls-og&quot;]/div/div[1]/div/button</value>
      <webElementGuid>c5a0013a-0a83-46db-93c8-e0ab3e6f6430</webElementGuid>
   </webElementProperties>
</WebElementEntity>
