<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create new group</name>
   <tag></tag>
   <elementGuidId>7fdc6acc-6940-46ac-917d-3cff2b34648f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12 > a.pull-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notification-group-row']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03fd95aa-a2c5-40e1-9ab4-12a4716c16de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/btportal/web/index.php?r=notification-group/index&amp;sid=409</value>
      <webElementGuid>6262d231-6434-45b8-866e-cdf4ea568428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>06ceb944-bdbe-44e9-8e88-d4acafe3b044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f3d28d83-232c-46d2-8757-83049df272a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create new group</value>
      <webElementGuid>5ea4a705-0af5-48db-b4d0-0c94dae7cd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notification-group-row&quot;)/div[@class=&quot;col-xs-12&quot;]/a[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>73706988-ca0e-4edc-a093-5fee460ce401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notification-group-row']/div/a</value>
      <webElementGuid>07d93e9b-419a-49df-9e6c-8ed76e3e72ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create new group')]</value>
      <webElementGuid>86915c99-be83-46fa-9015-2285e8fae3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::a[1]</value>
      <webElementGuid>d919ad5e-32a7-4275-9ce8-86fc198a1ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-OR-'])[2]/preceding::a[1]</value>
      <webElementGuid>10a9e6a3-edfb-4576-94ce-ed58f34f7616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create new group']/parent::*</value>
      <webElementGuid>3209dc41-1016-45d9-8c0d-df22c9560cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/btportal/web/index.php?r=notification-group/index&amp;sid=409')]</value>
      <webElementGuid>0b110af4-d07b-41c8-98d2-45e6877f427e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>885d7564-ba6f-4aa0-b6c6-831240125111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/btportal/web/index.php?r=notification-group/index&amp;sid=409' and (text() = 'Create new group' or . = 'Create new group')]</value>
      <webElementGuid>b3a20e62-0225-4665-a345-eb3c96b72a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
