<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Synthetic</name>
   <tag></tag>
   <elementGuidId>d711d07c-7d6e-424f-a094-a473d44c2732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;chartID_1&quot;][count(. | //*[(contains(text(), 'SYNTHETIC') or contains(., 'SYNTHETIC'))]) = count(//*[(contains(text(), 'SYNTHETIC') or contains(., 'SYNTHETIC'))])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;chartID_1&quot;]</value>
      <webElementGuid>fbc276bc-8044-4d1c-a950-c10a152ccc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SYNTHETIC</value>
      <webElementGuid>e7f6bc59-4e4d-4fbb-b692-f395d0828879</webElementGuid>
   </webElementProperties>
</WebElementEntity>
