<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DashboardTitle</name>
   <tag></tag>
   <elementGuidId>4b4a19b1-4d09-49d7-a27a-aa0f2af12ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;new-dashboard-item&quot;]/td[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;new-dashboard-item&quot;]/td[1]/input</value>
      <webElementGuid>2282625e-64c2-4188-bb9a-b31b0889e7c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
