<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Desktop</name>
   <tag></tag>
   <elementGuidId>f76006af-3a13-41f3-8744-ba3957e07087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;desktop-tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;desktop-tab&quot;]</value>
      <webElementGuid>cb43becc-a64e-4f86-9e81-f74d0bc015a1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
