<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_MetricTable1</name>
   <tag></tag>
   <elementGuidId>1a27065b-2061-4517-8570-a751812b6b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[1]</value>
      <webElementGuid>ea52de82-214e-4218-a1cb-da267feefaa8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
