<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_MetricTable3</name>
   <tag></tag>
   <elementGuidId>893f554e-1b90-4e59-86b6-1e78e0aa8d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[3]</value>
      <webElementGuid>98efb8ca-0060-4215-9f72-31cc74f2ec7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
