<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_MetricTable2</name>
   <tag></tag>
   <elementGuidId>b9298645-6409-4218-ac92-d8147eab19c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;metric-threshold-cards&quot;]/div/div[2]</value>
      <webElementGuid>368fc539-c286-48dc-bbcb-0aad4573240e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
